name: bunyan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  lucide_icons: ^0.395.0
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  timeago: ^3.6.1
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
