name: bonyan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core & UI Packages
  cupertino_icons: ^1.0.2
  lucide_flutter: ^0.542.0
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.3.0

  # State Management & Navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0

  # Utility Packages
  intl: ^0.20.2
  timeago: ^3.6.1
  collection: ^1.19.1

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/ # Added fonts directory

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900